### PR TITLE
CSS/HTML

### PR DESCRIPTION
**Pull request by Maris214**
I separated the container into 2 separate containers. One for the input field and one for the task list so the task list is still visible when adding tasks. Also created some CSS variables for the themes. I figured a default, a light, and a dark theme would be good to start with. Did not choose colors yet just set up the variables.

### CODE REVIEW

**Review by andystoys — CHANGES_REQUESTED** [review]
Congrats on creating your first PR! 🎊 

It's generally best to work off of your own branch so your changes don't conflict with others and only your changes get merged. @devtebaldi expressed that he was going to make changes on this branch so can you either 1) coordinate with him to create a single PR with all the changes or 2) create a separate branch with just your changes?

**Comment by andystoys** [comment]
Can you also update the title to better describe what the changes are? If we use general/vague titles it'll be harder to quickly identify the changes when looking at them later down the road.

**Comment by Maris214** [comment]
Yeah this pull request was a mistake. I didn't know how to do a pull request and did it wrong. Don't worry about this.

**Comment by andystoys** [comment]
No worries. Can you close this PR then? 🙏

**Pull request closed without merging**
