### PR TITLE
changed the position of the button

### PR DESCRIPTION
**Pull request by Tenkaklet**
### **PR Type**
enhancement, documentation

___

### **Description**
- Enhanced the overall styling of the application by adding global box-sizing and updating the body background with multiple images.
- Improved the `.container` class with relative positioning and a background image with opacity.
- Adjusted the input and button elements for better alignment and visual appeal.
- Integrated Google Fonts for improved typography.
- Updated the HTML structure to wrap the input and button in a `div` for better styling control.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>styles.css</strong><dd><code>Enhanced styling for layout and background images.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

src/css/styles.css
<li>Added global box-sizing rule.<br> <li> Updated body background with images and positioning.<br> <li> Enhanced <code>.container</code> with relative positioning and background image.<br> <li> Adjusted input and button styles for better alignment.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Code-Duddies/TaskMaster/pull/16/files#diff-506553736ec2a7007edf02fc6f203dc94a6f62054042f9148957f96270a7db22">+46/-11</a>&nbsp; </td>
</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>index.html</strong><dd><code>Integrated Google Fonts and improved input/button structure.</code></dd></summary>
<hr>

src/index.html
<li>Added Google Fonts preconnect and font link.<br> <li> Wrapped input and button in a <code>div</code> for better styling.<br>

</details>
    

  </td>
  <td><a href="https://github.com/Code-Duddies/TaskMaster/pull/16/files#diff-ce434ef5cc161194b450135a3586eb89357fc270e8aaa8e336db5a04e8d52fbe">+8/-3</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by Tenkaklet** [comment]
re opening due to my morning, need more coffee.
@andystoys + @JSCodes14 
approve this.

@devtebaldi good job! keep working on the styling!

**Comment by andystoys** [comment]
> re opening due to my morning, need more coffee. @andystoys + @JSCodes14 approve this.
> 
> @devtebaldi good job! keep working on the styling!

Can you coordinate with @devtebaldi on these changes? He might have some other pending changes as well.

**Comment by Tenkaklet** [comment]
> > re opening due to my morning, need more coffee. @andystoys + @JSCodes14 approve this.
> > @devtebaldi good job! keep working on the styling!
> 
> Can you coordinate with @devtebaldi on these changes? He might have some other pending changes as well.

When @devtebaldi sees this. Hopefully he'll get it working on it.

**Comment by Tenkaklet** [comment]
@devtebaldi are you satisfied with your work? Ok to merge it?

**Pull request merged**
